# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SchedulerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SchedulerWindow(object):
    def setupUi(self, SchedulerWindow):
        SchedulerWindow.setObjectName("SchedulerWindow")
        SchedulerWindow.resize(308, 125)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SchedulerWindow.sizePolicy().hasHeightForWidth())
        SchedulerWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(SchedulerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(100, 10, 201, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.target_label = QtWidgets.QLabel(self.centralwidget)
        self.target_label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.target_label.setObjectName("target_label")
        self.countdown_label = QtWidgets.QLabel(self.centralwidget)
        self.countdown_label.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.countdown_label.setObjectName("countdown_label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 201, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(60, 80, 75, 31))
        self.submit_button.setObjectName("submit_button")
        self.withdrew_button = QtWidgets.QPushButton(self.centralwidget)
        self.withdrew_button.setGeometry(QtCore.QRect(170, 80, 75, 31))
        self.withdrew_button.setObjectName("withdrew_button")
        SchedulerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SchedulerWindow)
        QtCore.QMetaObject.connectSlotsByName(SchedulerWindow)

    def retranslateUi(self, SchedulerWindow):
        _translate = QtCore.QCoreApplication.translate
        SchedulerWindow.setWindowTitle(_translate("SchedulerWindow", "关机计划"))
        self.target_label.setText(_translate("SchedulerWindow", "输入关机时间："))
        self.countdown_label.setText(_translate("SchedulerWindow", "关机倒计时："))
        self.submit_button.setText(_translate("SchedulerWindow", "提交"))
        self.withdrew_button.setText(_translate("SchedulerWindow", "撤销"))
